<div class="flex-box flex-box-justify-center flex-align-center full-height flex-vertical">
	<img src="${PATH}images/no-data2.png" width="100">
	<div class="gray9 margin-t_7rem font_85rem">
		{{msg}}
	</div>
	
	<div class="margin-t-1rem" data-id="call-box">
		<button type="button" class="button button-md button-fill border-none btn-blue" style="border-radius:1rem" onclick="commomLab.callTeacher();">
			<span class="padding-l_75rem padding-r_75rem">
				找老师
			</span>
		</button>
	</div>
</div>